# Generated by Django 4.0.3 on 2022-03-13 22:41

from django.db import migrations, models
import employee_menu_service.apps.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.CharField(default=employee_menu_service.apps.functions.get_clean_uuid, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Nombre de la comida')),
            ],
        ),
    ]
